### ISSUE TITLE
Update GoF for ZAP 2.3.x etc?

### ISSUE THREAD

**Issue by kingthorin** [hacktics/good-old-files#1]
Checkout this thread, there are a few things that GoF isn't doing quite properly these days:
https://groups.google.com/forum/#!topic/zaproxy-develop/AugCQ9_E3ng

It would be wonderful it if could be updated and added to the ZAP Marketplace.

**Comment by bbzap** [comment]
Anybody know if any progress is being made - I think this would be a great addition to the ZAP platform.

Looking forward to seeing it updated if possible - thanks in advance

**Comment by kingthorin** [comment]
Alternatives:
https://github.com/zaproxy/community-scripts/blob/master/active/gof_lite.js
https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/BackupFileDisclosure.java

Also ZAP's dirbuster support/integration is currently being simplified. Once that is done I may take a crack at forking GoF and updating it.

**Comment by pentagramz** [comment]
How do I add .java extension in zap?

**Comment by kingthorin** [comment]
@pentagramz that question is probably best asked in the ZAP user or developer groups.

* https://groups.google.com/forum/m/#!forum/zaproxy-users
* https://groups.google.com/forum/m/#!forum/zaproxy-develop

**Comment by kingthorin** [comment]
It seems GoF is abandon. There are various alternatives as outlined earlier. Closing.
